// Copyright 2018 2018 BY JIAXUAN
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/jiaxuanzhou/jx-controller/pkg/apis/jx/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// JxTaskLister helps list JxTasks.
type JxTaskLister interface {
	// List lists all JxTasks in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.JxTask, err error)
	// JxTasks returns an object that can list and get JxTasks.
	JxTasks(namespace string) JxTaskNamespaceLister
	JxTaskListerExpansion
}

// jxTaskLister implements the JxTaskLister interface.
type jxTaskLister struct {
	indexer cache.Indexer
}

// NewJxTaskLister returns a new JxTaskLister.
func NewJxTaskLister(indexer cache.Indexer) JxTaskLister {
	return &jxTaskLister{indexer: indexer}
}

// List lists all JxTasks in the indexer.
func (s *jxTaskLister) List(selector labels.Selector) (ret []*v1alpha1.JxTask, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.JxTask))
	})
	return ret, err
}

// JxTasks returns an object that can list and get JxTasks.
func (s *jxTaskLister) JxTasks(namespace string) JxTaskNamespaceLister {
	return jxTaskNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// JxTaskNamespaceLister helps list and get JxTasks.
type JxTaskNamespaceLister interface {
	// List lists all JxTasks in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.JxTask, err error)
	// Get retrieves the JxTask from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.JxTask, error)
	JxTaskNamespaceListerExpansion
}

// jxTaskNamespaceLister implements the JxTaskNamespaceLister
// interface.
type jxTaskNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all JxTasks in the indexer for a given namespace.
func (s jxTaskNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.JxTask, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.JxTask))
	})
	return ret, err
}

// Get retrieves the JxTask from the indexer for a given namespace and name.
func (s jxTaskNamespaceLister) Get(name string) (*v1alpha1.JxTask, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("jxtask"), name)
	}
	return obj.(*v1alpha1.JxTask), nil
}
