// Copyright 2018 2018 BY JIAXUAN
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/jiaxuanzhou/jx-controller/pkg/apis/jx/v1alpha1"
	scheme "github.com/jiaxuanzhou/jx-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JxTasksGetter has a method to return a JxTaskInterface.
// A group's client should implement this interface.
type JxTasksGetter interface {
	JxTasks(namespace string) JxTaskInterface
}

// JxTaskInterface has methods to work with JxTask resources.
type JxTaskInterface interface {
	Create(*v1alpha1.JxTask) (*v1alpha1.JxTask, error)
	Update(*v1alpha1.JxTask) (*v1alpha1.JxTask, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.JxTask, error)
	List(opts v1.ListOptions) (*v1alpha1.JxTaskList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JxTask, err error)
	JxTaskExpansion
}

// jxTasks implements JxTaskInterface
type jxTasks struct {
	client rest.Interface
	ns     string
}

// newJxTasks returns a JxTasks
func newJxTasks(c *JiaxuanV1alpha1Client, namespace string) *jxTasks {
	return &jxTasks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jxTask, and returns the corresponding jxTask object, and an error if there is any.
func (c *jxTasks) Get(name string, options v1.GetOptions) (result *v1alpha1.JxTask, err error) {
	result = &v1alpha1.JxTask{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jxtasks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JxTasks that match those selectors.
func (c *jxTasks) List(opts v1.ListOptions) (result *v1alpha1.JxTaskList, err error) {
	result = &v1alpha1.JxTaskList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jxtasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jxTasks.
func (c *jxTasks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jxtasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a jxTask and creates it.  Returns the server's representation of the jxTask, and an error, if there is any.
func (c *jxTasks) Create(jxTask *v1alpha1.JxTask) (result *v1alpha1.JxTask, err error) {
	result = &v1alpha1.JxTask{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jxtasks").
		Body(jxTask).
		Do().
		Into(result)
	return
}

// Update takes the representation of a jxTask and updates it. Returns the server's representation of the jxTask, and an error, if there is any.
func (c *jxTasks) Update(jxTask *v1alpha1.JxTask) (result *v1alpha1.JxTask, err error) {
	result = &v1alpha1.JxTask{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jxtasks").
		Name(jxTask.Name).
		Body(jxTask).
		Do().
		Into(result)
	return
}

// Delete takes name of the jxTask and deletes it. Returns an error if one occurs.
func (c *jxTasks) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jxtasks").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jxTasks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jxtasks").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched jxTask.
func (c *jxTasks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JxTask, err error) {
	result = &v1alpha1.JxTask{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jxtasks").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
